export const ActionTypes = {
  ADD_PRODUCTS: "ADD_PRODUCTS",
  HOWMANY_PRODUCT: "HOWMANY_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  LOG_IN: "LOG_IN",
  HANDLE_CUSTOMER_INFO: "HANDLE_CUSTOMER_INFO",
  HANDLE_DELIVERY_MODE: "HANDLE_DELIVERY_MODE",
  RESTART_CART: "RESTART_CART",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  NUM_OF_MODALS: "NUM_OF_MODALS",
};
